name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run Linter
        run: pnpm lint

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Run Tests
        run: pnpm run test

  publish:
    name: Publish to NPM
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Build project
        run: pnpm build
      - name: Create Versions and Changelogs
        run: pnpm changeset version
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kas-elvirov/kas-tools.git
          git add .
          git commit -m "chore: versions and changelog update"
          git push
      - name: Publish with Changesets
        run: pnpm exec changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
