name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Run Linter
        run: pnpm lint

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Run Tests
        run: pnpm run test

  publish:
    name: Publish to NPM
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Build project
        run: pnpm build
      - name: Publish with Changesets
        run: pnpm exec changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
